In [7]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_tech.csv", encoding="utf-8")
display(df_vendas)

df_gerentes = pd.read_excel("gerentes_lojas.xlsx")
display(df_gerentes)

/var/folders/_8/hgf1z0gx1zx6jb2pcsd2t9br0000gn/T/ipykernel_48879/3946260516.py:4: DtypeWarning: Columns (0: Data_Base) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv("vendas_tech.csv", encoding="utf-8")

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

                `   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [16]:
# inspeção dos dados
display(df_vendas)
display(df_vendas.head())
display(df_vendas.tail())
display(df_vendas.sample(20))
display(df_vendas.shape)
display(list(df_vendas.columns))
display(df_vendas.info())
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
99993,99994,2024-07-01,Curitiba,Mouse Gamer,120.0,2,Cliente_22176,NaN
92735,92736,2024-11-03,São Paulo,"Monitor 27""",1200.0,2,Cliente_2745,NaN
81411,81412,2023-10-30,Porto Alegre,Notebook HP,3200.0,1,Cliente_27167,NaN
17659,17660,2023-09-30,Curitiba,"Monitor 27""",1200.0,1,Cliente_26312,NaN
48284,48285,2024-11-18,Salvador,Cabo HDMI,40.0,3,Cliente_22031,NaN
98546,98547,2023-01-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_18297,NaN
5295,5296,2024-11-21,Porto Alegre,Cabo HDMI,40.0,1,Cliente_10502,NaN
91461,91462,2023-04-05,Belo Horizonte,iPhone 14,5500.0,1,Cliente_17575,NaN
19716,19717,2024-01-01,Belo Horizonte,"Monitor 27""",1200.0,1,Cliente_25604,NaN
92022,92023,2024-08-12,Porto Alegre,Cabo HDMI,40.0,1,Cliente_26480,NaN
12562,12563,2023-08-23,Curitiba,Smartphone Samsung,2200.0,1,Cliente_17422,NaN
21205,21206,2024-02-21,Curitiba,Notebook Dell,3500.0,1,Cliente_2594,NaN
79426,79427,2023-01-09,Porto Alegre,"Monitor 27""",1200.0,1,Cliente_14217,NaN
97843,97844,2024-01-18,Belo Horizonte,"Monitor 27""",1200.0,2,Cliente_20257,NaN
82757,82758,2024-01-31,Recife,Smartphone Samsung,2200.0,1,Cliente_14211,NaN
32352,32353,2023-06-02,Porto Alegre,Mouse Gamer,120.0,1,Cliente_10997,NaN
40387,40388,2024-06-01,Belo Horizonte,"Monitor 27""",1200.0,1,Cliente_24735,NaN
11317,11318,2023-02-26,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_6694,NaN
41315,41316,2023-04-08,Belo Horizonte,Notebook HP,3200.0,1,Cliente_6909,NaN
52660,52661,2023-07-03,Salvador,"Monitor 27""",1200.0,1,Cliente_8168,NaN

(100100, 8)

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [37]:
# tratamento de dados
# display(df_vendas["Loja"])
# df_novo = df_vendas[["Loja", "Cliente"]]
# display(df_vendas[["Loja", "Cliente"]])

# colunas
df_analise = df_vendas.drop(columns=["Data_Base"])

# nulos
# df_analise = df_analise.dropna() # exclui as linhas com valores nulos
df_analise["Loja"] = df_analise["Loja"].fillna("Online") 

# tipos de dados
df_analise["Data"] = (pd.to_datetime(df_analise["Data"], format="%Y-%m-%d"))

# padronização
df_analise["Loja"] = df_analise["Loja"].str.strip()
df_analise["Loja"] = df_analise["Loja"].str.title()

# valores duplicados
df_analise = df_analise.drop_duplicates(subset=["ID_Pedido"], keep="first")


display(df_analise)
display(df_analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 5.3 MB

None

In [ ]:
# criação de novas colunas
# faturamento
df_analise["Faturamento"] = df_analise["Qtd"] * df_analise["Preco_Unitario"]

# forma de venda
df_analise["Forma_de_Venda"] = np.where(df_analise["Loja"] == "Online", "Online", "Presencial")

# regiao
display(df_analise["Loja"].unique())
df_analise["Regiao"] = np.where(df_analise["Loja"].

display(df_analise)

<StringArray>
[     'São Paulo', 'Belo Horizonte',         'Online', 'Rio De Janeiro',
       'Salvador',         'Recife',       'Curitiba',   'Porto Alegre']
Length: 8, dtype: str

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial
...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial